# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: variables-frontcore

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g firebase-tools
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    firebase deploy --token $(FIREBASE_TOKEN)
    echo "Firebase token: $(token-firebase)"
  displayName: 'Inclusao do Token do Firebase'